apiVersion: apps/v1
kind: Deployment
metadata:
  name: listener-service
  labels:
    app: listener-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: listener-service
  template:
    metadata:
      labels:
        app: listener-service
    spec:
      containers:
      - name: listener-service
        image: 'andersonmarquesdocker/listener-service:1.0.1'
        ports:
          - containerPort: 80
        env:
          - name: BROKER_URL
            value: "http://broker-service.info"
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: listener-service
spec:
  selector:
    app: listener-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80