apiVersion: apps/v1
kind: Deployment
metadata:
  name: mail-service
  labels:
    app: mail-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mail-service
  template:
    metadata:
      labels:
        app: mail-service
    spec:
      containers:
      - name: mail-service
        image: 'andersonmarquesdocker/mail-service:1.0.1'
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        env:
        - name: MAIL_DOMAIN
          value: ""
        - name: MAIL_HOST
          value: "localhost"
        - name: MAIL_PORT
          value: "1025"
        - name: MAIL_USER
          value: ""
        - name: MAIL_PASS
          value: ""
        - name: MAIL_ENCRYPTION
          value: "none"
        - name: MAIL_FROM
          value: "Anderson Marques"
        - name: MAIL_ADDRESS
          value: "anderson@example.com"

---
apiVersion: v1
kind: Service
metadata:
  name: mail-service
spec:
  selector:
    app: mail-service
  ports:
  - protocol: TCP
    name: mail-service
    port: 80
    targetPort: 80
